name: Isometric Calender
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 19 * * *"}]
  # Lines below let you run workflow manually and on each commit
  #workflow_dispatch:
  #push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: vasu-1/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: vasu-1
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          # Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year